# Generated by Django 4.2.2 on 2023-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Customer', 'customer'), ('Shopper', 'shopper')], default='Customer', help_text='account type', max_length=12, verbose_name='Account type'),
        ),
    ]
