# Generated by Django 4.2.1 on 2023-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Customer', 'customer'), ('Shopper', 'shopper'), ('Vendor', 'vendor')], default='Customer', help_text='account type', max_length=12, verbose_name='Account type'),
        ),
    ]
