# Generated by Django 4.2.1 on 2023-06-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopperprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='date_cerated',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shopperprofile',
            name='state',
        ),
    ]
