# Generated by Django 4.2.1 on 2023-07-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_user_userprofile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_cerated',
            new_name='date_created',
        ),
        migrations.DeleteModel(
            name='ShopperProfile',
        ),
    ]
