# Generated by Django 4.2.1 on 2023-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperpersonalinfo',
            name='driving_skill',
            field=models.CharField(blank=True, choices=[('None', "I don't know how to drive"), ('Learner', "I'm currently learning how to drive"), ('Intermediate', 'I have intermediate skills'), ('Expert', 'I am an expert driver')], help_text='How would you rate your driving?', max_length=100, null=True),
        ),
    ]
