# Generated by Django 4.2.1 on 2023-06-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock_qty', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='Ibadan', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(default='Oyo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.CharField(default='Bodija', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='My Store', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory', to='stores.store'),
        ),
        migrations.AddConstraint(
            model_name='storeinventory',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='follow once'),
        ),
    ]
