# Generated by Django 4.2.2 on 2023-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default='Lagos', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(default='Lagos', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='my store', max_length=50),
            preserve_default=False,
        ),
    ]
