# Generated by Django 4.2.2 on 2023-11-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category'),
        ),
    ]
