# Generated by Django 4.2.1 on 2023-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeinventory_store_city_store_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
