# Generated by Django 4.2.2 on 2023-12-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_latitube_store_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='latitube',
            new_name='latitude',
        ),
    ]
