# Generated by Django 4.2.2 on 2023-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_storeproduct_images_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='images',
            field=models.ManyToManyField(blank=True, to='stores.productimage'),
        ),
    ]
