# Generated by Django 4.2.2 on 2024-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_latitube_store_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
