# Generated by Django 4.2.1 on 2023-06-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_balance_alter_storeinventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='stock_qty',
            field=models.IntegerField(default=1),
        ),
    ]
