# Generated by Django 4.2.1 on 2023-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_storeinventory_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinventory',
            old_name='price',
            new_name='retail_price',
        ),
        migrations.RemoveField(
            model_name='storeinventory',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
