# Generated by Django 4.2.2 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_been_picked_up',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_been_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
