# Generated by Django 4.2.2 on 2023-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Available', 'available'), ('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Available', max_length=50),
        ),
    ]
