# Generated by Django 4.2.2 on 2023-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_has_been_picked_up_remove_order_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='orders/qr_codes/'),
        ),
    ]
