# Generated by Django 4.2.2 on 2023-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='destination_address',
            new_name='delivery_address',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
